### ISSUE TITLE
database is not inheriting emails from one database to another

### ISSUE THREAD

**Issue by rugger403** [godot-dabz/wdi_attendance#10]
We are trying to grab the email address entered from one database to another not the email_id. I've tried t.references :user, :emails and t.references :user.email neither work. Can you provide some help?

**Comment by phlco** [comment]
Please provide links to any files you might be referencing. What databases are you talking about? Your application will only have one database per-environment, unless you mean tables. Please elaborate.

**Comment by slchase** [comment]
Thanks....we resolved the issue with the table reference.

**Comment by phlco** [comment]
Awesome! What was the solution?
