### ISSUE TITLE
Github 

### ISSUE THREAD

**Issue by slchase** [godot-dabz/wdi_attendance#14]
Unable to execute pull request

**Comment by phlco** [comment]
What error are you having? Please be more specific.

**Comment by slchase** [comment]
Dain did a push/pull that appeared ok.  Upon pull request, he got rejection re: "We can’t automatically merge this pull request. Use the command line to resolve conflicts before continuing.".  Command line code appears resulted in a new branch.  Sarah did not receive pull request.  Thanks

**Comment by phlco** [comment]
Close your pull request and merge the upstream master branch locally.  Then resolve any merge conflicts there before pushing again.
