### ISSUE TITLE
has_many :through associations do not support polymorphic access to the associated object. 

### ISSUE THREAD

**Issue by slchase** [godot-dabz/wdi_attendance#27]
I think this is the problem we're having

**Comment by phlco** [comment]
What feature are you working on?
Please paste in any errors you've received.

**Comment by slchase** [comment]
feature: producer view lateness totals by cohort

Cohort.first.attendances
  Cohort Load (0.4ms)  SELECT  "cohorts".* FROM "cohorts"  ORDER BY "cohorts"."id" ASC LIMIT 1
NoMethodError: undefined method `attendances' for #<Cohort:0x007fded0040f90>
from /Users/Sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'

**Comment by slchase** [comment]
The polymorphic access workaround worked!

**Comment by phlco** [comment]
:+1:
