### ISSUE TITLE
How to use ruby variable in JS file

### ISSUE THREAD

**Issue by slchase** [godot-dabz/wdi_attendance#33]
Tried gon gem but failed.  Any ideas?  We're trying to pass lateness data to the chart.  Thanks!

**Comment by h4w5** [comment]
@slchase if you rename your js file: `file.js.erb` you can use erb in it, like:

```javascript
var name = <%= @current_user.name %>
``

**Comment by phlco** [comment]
Careful! Rails will render the above __without__ quotes.

```js
var name = Simons
//  Uncaught ReferenceError: Simons is not defined
```

To correctly embed it be sure to wrap the ERB portion in quotes.

```js
var name = '<%= @current_user.name %>'
```

**Comment by h4w5** [comment]
Correct, Phil! 10 points for Slytherin!
